# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Slidict.Wip
PackageVersion: 2.10.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wip.exe
  PortableCommandAlias: wip
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/slidict/wip/releases/download/v2.10.0/wip-2.10.0-win-x64.zip
  InstallerSha256: 140C762C666A5E79C5EEC50928EB48EF70F7B327FC7CA1F1287B0507DC2E5A8A
ManifestType: installer
ManifestVersion: 1.12.0
